<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="A2ML22312" name="com.mindtree.sfdc.Script.MainTest" tests="4" failures="0" timestamp="05 Jun 2018 13:11:56 GMT" time="22.359" errors="1">
  <testcase name="testScenarios" time="10.929" classname="com.mindtree.sfdc.Script.MainTest"/>
  <testcase name="testScenarios" time="9.910" classname="com.mindtree.sfdc.Script.MainTest"/>
  <testcase name="endFrameWork" time="1.519" classname="com.mindtree.sfdc.Script.MainTest">
    <error type="java.lang.IllegalArgumentException" message="D:\Automation\Training\Framework\SalesForce\csv does not exist">
      <![CDATA[java.lang.IllegalArgumentException: D:\Automation\Training\Framework\SalesForce\csv does not exist
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:886)
at com.mindtree.sfdc.Script.BaseTest.endFrameWork(BaseTest.java:126)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- endFrameWork -->
  <testcase name="testScenarios" time="0.001" classname="com.mindtree.sfdc.Script.MainTest">
    <skipped/>
  </testcase> <!-- testScenarios -->
</testsuite> <!-- com.mindtree.sfdc.Script.MainTest -->
